services:
  inspector:
    image: workload-inspector:latest
    environment:
      - container=true
      - INSPECTOR_HTTP_PORT=8000
      - INSPECTOR_HTTP_AUTH=true
    env_file:
      - .env
    ports:
      - 8000:8000
